location = "westeurope"
Owner = "QRIT"
CC = "625"
Environment = "Production"
vnetname = "qrspoke1-vnet"
resourcegroupname = "qrspoke1-rg"
Subnetname = "Apps"
NetworkSecurityGroup = "Apps-Subnet-nsg"