location = "westeurope"
Owner = "QRIT"
CC = "625"
Environment = "Production"
vnetname = "qrhub1-vnet"
resourcegroupname = "qrhub1-rg"
Subnetname = "Firewall"
NetworkSecurityGroup = "Firewall-Subnet-nsg"